project5/app5/urls.py
from django.conf.urls import url
from . import views


app_name = 'app5'

urlpatterns = [
    
    url(r'^help/$', views.help, name = "help")
]

project5/project5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app5 import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^admin/', admin.site.urls),
    url(r'^app5/', include('app5.urls')),
    url(r'^signup/', views.signup, name = "signup"),
    url(r'^user_logout/', views.user_logout, name = "user_logout"),
    url(r'^special/',views.special, name="special"),
    url(r'^user_login/', views.user_login, name="user_login"),
]

project5/app5/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User) #to add more attributes to the user

    #additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

project5/app5/forms.py
from django import forms
from django.contrib.auth.models import User
from app5.models import UserProfileInfo

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

project5/app5/views.py
from django.shortcuts import render
from . import forms

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'app5/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def signup(request):

    registered = False


    if request.method == "POST":
        user_form = forms.Userform(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user #oneonone relationship between user and profile

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            if 'portfolio_site' in request.FILES:
                profile.portfolio_site = request.FILES['portfolio_site']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
            user_form = forms.Userform()
            profile_form = forms.UserProfileInfoForm()
    return render(request, 'app5/signup.html',
                            {'Userform': user_form,
                            'UserProfileInfoForm': profile_form,
                            'registered': registered})


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('special'))
            else:
                return HttpResponse("Account is not active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request,'app5/login.html',{})


@login_required
def special(request):
    return render(request, 'app5/special.html',{})











#
def help(request):
    return render(request, 'app5/helppage.html')

project5/templates/app5/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'signup' %}">Signup</a></li>
          <li><a class="navbar-link" href="{% url 'app5:help' %}">Help</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'user_logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'user_login' %}">Login</a></li>
          {% endif %}



        </ul>

        <form class="form-inline my-2 my-lg-0 pull-right">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

        </form>

      </div>

    </nav>
    <div class="container">
      {% block body_block %}
      <!-- anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

project5/templates/app5/helppage.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
  {% block body_block%}
    <h1>How can we help you today?</h1>
  {% endblock %}

project5/templates/app5/index.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
{% load customtemplates %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to Headless Babe</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p>We would like to know you more.</p>
  <p>Please go to our <a href="{% url 'signup' %}"}>signup</a> page to join our mailing list</p>
  <p>If you need some help, refer to our <a href="{% url 'app5:help' %}">help page</a>.</p>
  <p> <a href="{% url 'admin:index' %}">Admin page</a>  </p>
  {{ text|cut:"Hello" }}
  {{ number|add:"99" }}
</div>


    {% endblock %}

project5/templates/app5/login.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
  {% block body_block %}

  <div class="jumbotron">
    <h1>Fill in the form below to login to your account</h1>
    <form class=""  method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" value="" placeholder="Enter username here">

      <label for="password">Password:</label>
      <input type="password" name="password" value="">

      <input type="submit" name="" value="login">

    </form>


  </div>
  {% endblock %}

project5/templates/app5/signup.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
{% block body_block %}
{% load staticfiles %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}
      <h2><em>Please fill out the signup form below to signup</em></h2>
      <form class="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ Userform.as_p }}
        {{ UserProfileInfoForm.as_p}}

        <input type="submit" class= "btn btn-default" name="" value="Submit">

      </form>

  {% endif%}

</div>



    {% endblock %}

project5/templates/app5/special.html
<!DOCTYPE html>
{% extends 'app5/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h2>You are now signed in!</h2>

    </div>




    {% endblock%}